apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: ziptrade-in-tls
spec:
  secretName: ziptrade-in
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ziptrade.in
  dnsNames:
    - ziptrade.in
    - www.ziptrade.in